name: ml_example_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyterlab>=4.2
  - notebook>=7.2
  - ipykernel>=6.29
  - numpy>=1.26
  - pandas>=2.2
  - scipy>=1.13
  - scikit-learn>=1.5
  - matplotlib>=3.8
  - seaborn>=0.13
  - plotly>=5.22
  - python-dotenv>=1.0
  - pip
  - pip:
      - ucimlrepo
